// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmR4TAIElClBuFUjayvs9cXSXbDhalvtA',
    appId: '1:395043461043:web:dee418e81e106f0627ddc6',
    messagingSenderId: '395043461043',
    projectId: 'padel-arena-5b4cb',
    authDomain: 'padel-arena-5b4cb.firebaseapp.com',
    storageBucket: 'padel-arena-5b4cb.appspot.com',
    measurementId: 'G-ZPP12B5G7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWlFB2y_VJY9d3OlJtLNdcEQrZOp0ktOc',
    appId: '1:395043461043:android:3f18929cd40982ca27ddc6',
    messagingSenderId: '395043461043',
    projectId: 'padel-arena-5b4cb',
    storageBucket: 'padel-arena-5b4cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGM92FWT7M0m_KGeeutGCJ-297R1uOFOg',
    appId: '1:395043461043:ios:bc0a02b7e5bbb4da27ddc6',
    messagingSenderId: '395043461043',
    projectId: 'padel-arena-5b4cb',
    storageBucket: 'padel-arena-5b4cb.appspot.com',
    iosClientId: '395043461043-osuhi9t35ar4o13v930vhimqf4gkvldl.apps.googleusercontent.com',
    iosBundleId: 'com.example.padelArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGM92FWT7M0m_KGeeutGCJ-297R1uOFOg',
    appId: '1:395043461043:ios:bc0a02b7e5bbb4da27ddc6',
    messagingSenderId: '395043461043',
    projectId: 'padel-arena-5b4cb',
    storageBucket: 'padel-arena-5b4cb.appspot.com',
    iosClientId: '395043461043-osuhi9t35ar4o13v930vhimqf4gkvldl.apps.googleusercontent.com',
    iosBundleId: 'com.example.padelArena',
  );
}
